"""
generate_paper_outputs.py — reproduce every figure and table in the paper.

Paper structure
---------------
Figure 1  (§4.1)  (a) Pre/post kNN overlap  (b) CLIP-reference overlap
Figure 2  (§4.2)  Connector inversion quality vs semantic degradation (scatter)
Figure 3  (§4.3)  Controlled-perturbation curves: (a) low-rank, (b) masking
Table 1   (§4.2)  Correlation: reproj quality → semantic metrics
Table 2   (§4.2)  Qualitative caption examples  (hand-curated, no script)
Table 3   (§4.1)  Spectral diagnostics (post-connector)

Usage
-----
    python generate_paper_outputs.py            # all outputs
    python generate_paper_outputs.py --tables   # tables only (no heavy figure rerun)
"""

import argparse
import shutil
from pathlib import Path

# ---------------------------------------------------------------------------
# Figure manifest: paper label → source path (already generated by knn/plot scripts)
# ---------------------------------------------------------------------------
FIGURE_MANIFEST = {
    "fig1a": "figures/knn/single_dataset_topk_all.png",              # pre/post KNOR vs k (all models)
    "fig1b": "figures/knn_clip/single_dataset_topk_with_clip.png",   # CLIP-reference kNNOR
    "fig2":  "figures/caption_recon/fig_corr_scatter.png",           # scatter + regression (§4.2)
    "fig3a": "figures/lowrank_drop.png",                             # low-rank perturbation (§4.3)
    "fig3b": "figures/mask_drop.png",                                # token-mask perturbation (§4.3)
}

PAPER_DIR = Path("figures/paper")


def copy_figures():
    PAPER_DIR.mkdir(parents=True, exist_ok=True)
    for label, src_str in FIGURE_MANIFEST.items():
        src = Path(src_str)
        if not src.exists():
            print(f"  [missing] {label}: {src}")
            continue
        dst = PAPER_DIR / f"{label}{src.suffix}"
        shutil.copy2(src, dst)
        print(f"  {label} → {dst}")


# ---------------------------------------------------------------------------
# Tables — delegate to plot_caption_recon functions
# ---------------------------------------------------------------------------

def run_tables():
    from plot_caption_recon import load_all, make_corr_table, make_spectral_table

    print("\n[Table 1] Loading caption data...")
    df = load_all()
    print(f"  {len(df)} rows")
    make_corr_table(df)

    print("\n[Table 3] Spectral diagnostics...")
    make_spectral_table()


# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--tables", action="store_true", help="tables only, skip figure copying")
    p.add_argument("--figures", action="store_true", help="figures only, skip tables")
    args = p.parse_args()

    do_figs   = not args.tables
    do_tables = not args.figures

    if do_figs:
        print("\n=== Collecting paper figures → figures/paper/ ===")
        copy_figures()

    if do_tables:
        print("\n=== Generating paper tables → results/ ===")
        run_tables()

    print("\nPaper output manifest:")
    print("  Figure 1a  → figures/paper/fig1a.png   (source: figures/knn/single_dataset_topk_all.png)")
    print("  Figure 1b  → figures/paper/fig1b.png   (source: figures/knn_clip/single_dataset_topk_with_clip.png)")
    print("  Figure 2   → figures/paper/fig2.png    (source: figures/caption_recon/fig_corr_scatter.png)")
    print("  Figure 3a  → figures/paper/fig3a.png   (source: figures/lowrank_drop.png)")
    print("  Figure 3b  → figures/paper/fig3b.png   (source: figures/mask_drop.png)")
    print("  Table 1    → results/caption_recon_correlations.tex")
    print("  Table 3    → results/spectral_diagnostics.tex")
    print("  Table 2    → hand-curated (see paper §4.2)")


if __name__ == "__main__":
    main()
